name: refresh_interceptor_example
description: Flutter example for refresh_interceptor.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  refresh_interceptor:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
